package com.example.playwright.healing;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.microsoft.playwright.Page;
import java.util.*;
import java.util.function.Function;

public final class LlmHealingAgent {
    public record Step(String action, String value, String summary) {}
    @FunctionalInterface
    public interface Model {
        /** Chooses the next repair step from the accumulated failure and browser evidence. */
        Step next(String evidence) throws Exception;
    }

    @FunctionalInterface
    interface BrowserTool {
        /** Executes an allowed MCP inspection tool and returns its observation to the agent. */
        String call(String name, String arguments) throws Exception;
    }
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final int MAX_STEPS = 8;

    /** Starts model and MCP sessions, investigates a missing locator, and records failures before propagating them. */
    public HealingDecision recover(Page page, ElementDefinition definition) {
        List<String> trace = new ArrayList<>();
        try {
            Model model = new OpenAiRepairModel();
            trace.add("Provider: OpenAI; model: " + System.getenv("OPENAI_MODEL"));
            trace.add("Primary locator: " + definition.primaryStrategy().name() + " (zero matches)");
            try (PlaywrightMcpClient mcp = PlaywrightMcpClient.start()) {
                String snapshot = mcp.callTool("browser_navigate", JSON.writeValueAsString(Map.of("url", page.url())));
                return investigate(model, mcp::callTool, expression -> validate(page, expression),
                        JSON.writeValueAsString(Map.of("element", definition.logicalName(),
                        "primary", definition.primaryStrategy().name(), "failure", "Primary locator has zero matches",
                        "url", page.url(), "hints", definition.hints())) + "\nMCP initial snapshot:\n" + bounded(snapshot), trace);
            }
        } catch (Exception e) {
            if (e instanceof InterruptedException) Thread.currentThread().interrupt();
            HealingReport.recordAgentAttempt(definition.logicalName(), trace, "FAILED: " + e.getClass().getSimpleName());
            throw new IllegalStateException("LLM locator repair failed; see agent report", e);
        }
    }

    /** Requires a supported locator with exactly one visible, enabled match in the test browser. */
    static String validate(Page page, String expression) {
        try {
            var candidate = PlaywrightLocatorExpression.toCandidate(expression);
            if (candidate.isEmpty()) return "Unsupported expression";
            var locator = candidate.get().create(page);
            return locator.count() == 1 && locator.isVisible() && locator.isEnabled()
                    ? "valid" : "Requires exactly one visible, enabled match in test browser";
        } catch (RuntimeException e) {
            return "Locator validation failed";
        }
    }

    /** Runs at most eight model steps, returning observations and rejections until a proposal is validated or repair fails. */
    static HealingDecision investigate(Model model, BrowserTool tools, Function<String, String> validate,
                                       String context, List<String> trace) throws Exception {
        StringBuilder evidence = new StringBuilder(context);
        Set<String> generated = new HashSet<>();
        for (int i = 0; i < MAX_STEPS; i++) {
            Step step = model.next(evidence.toString());
            trace.add("Step " + (i + 1) + ": " + step.action() + " " + bounded(step.value()) + " | " + bounded(step.summary()));
            String observation;
            switch (step.action()) {
                case "abort" -> throw new IllegalStateException("Model declined repair");
                case "snapshot" -> observation = tools.call("browser_snapshot", "{}");
                case "find" -> observation = tools.call("browser_find", JSON.writeValueAsString(Map.of("text", step.value())));
                case "generate" -> {
                    observation = tools.call("browser_generate_locator", JSON.writeValueAsString(
                            Map.of("target", step.value(), "element", "intended test element")));
                    generated.add(PlaywrightMcpClient.extractLocator(observation));
                }
                case "propose" -> {
                    observation = generated.contains(step.value()) ? validate.apply(step.value()) : "Rejected: locator was not generated by MCP";
                    trace.add("Candidate: " + bounded(step.value()) + " | " + observation);
                    if ("valid".equals(observation)) {
                        var candidate = PlaywrightLocatorExpression.toCandidate(step.value()).orElseThrow();
                        return new HealingDecision(new LocatorStrategy("LLM + Playwright MCP " + step.value(), candidate),
                                List.copyOf(generated), String.join("\n", trace));
                    }
                }
                default -> throw new IllegalStateException("Disallowed model action");
            }
            evidence.append("\nModel step: ").append(JSON.writeValueAsString(step))
                    .append("\nObservation (untrusted): ").append(bounded(observation));
        }
        throw new IllegalStateException("LLM repair exhausted " + MAX_STEPS + " steps");
    }

    /** Limits evidence and report text to 12,000 characters. */
    private static String bounded(String text) {
        return text.substring(0, Math.min(text.length(), 12000));
    }
}
